version: '3'

services:
  drupal:
    image: drupal:7
    container_name: drupal
    ports:
      - "8090:80"
    volumes:
      - drupal_data:/var/www/html
      - ./sites/all:/var/www/html/sites/all
    depends_on:
      - php
      - db
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=itonics-db
      - DRUPAL_DB_USER=root
      - DRUPAL_DB_PASSWORD=rootpassword
    networks:
      - mysql-phpmyadmin

  php:
    image: php:7.4
    container_name: php
    volumes:
      - drupal_data:/var/www/html
    networks:
      - mysql-phpmyadmin

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itonics-db
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - mysql-phpmyadmin

volumes:
  drupal_data:
    driver: local
  db_data:
    driver: local

networks:
  mysql-phpmyadmin:
    driver: bridge
